In [62]:
# coding:utf8
import numpy as np

In [63]:
'''
https://crossincode.com/vip/homework/210/

任务1：利用 numpy 读取 csv 文件数据，命名为 iris，并以 ndarry 形式展示出来（阅读参考文章①）

https://blog.csdn.net/u012413551/article/details/87890989
-- str 参数，字符串处理 (默认情况下，数据被认为是float类型)
-- skiprows = 1  跳过首行 
-- usecols参数介绍一个元组，元组里面用列索引来指定输入特定的列。
-- -- usecols = (0,2) 第一、第二、第三列
-- -- 指定顺序：

'''
with open("iris.csv", encoding = 'utf-8') as f:
    data = np.loadtxt(f,delimiter = ",")
data

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [64]:
'''
任务2  找出原数据中最小值和最大值出现的位置（任务提示：numpy 中 argmax 和 argmin 函数可以定位到最大值和最小值的索引位置。阅读参考文章②）
https://blog.csdn.net/lanchunhui/article/details/50044417
'''
max_index = np.argmax(data)
min_index = np.argmin(data)

In [65]:
'''
任务3：利用 numpy 找出花萼最小值与最大值（阅读参考文章②）
'''
max_value = max(data)
min_value = min(data)
# max_value = data.max()
# min_value = data.min()

In [66]:
'''
任务4：将 iris 原数据进行从小到大排序，并以 ndarray 形式展示出来
（任务提示：排序函数为 sort。阅读参考文章③）
https://www.jb51.net/article/52730.htm
'''
data.sort()
data

array([4.3, 4.4, 4.4, 4.4, 4.5, 4.6, 4.6, 4.6, 4.6, 4.7, 4.7, 4.8, 4.8,
       4.8, 4.8, 4.8, 4.9, 4.9, 4.9, 4.9, 4.9, 4.9, 5. , 5. , 5. , 5. ,
       5. , 5. , 5. , 5. , 5. , 5. , 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1,
       5.1, 5.1, 5.2, 5.2, 5.2, 5.2, 5.3, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4,
       5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.6, 5.6, 5.6, 5.6, 5.6, 5.6,
       5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.8, 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 5.9, 5.9, 5.9, 6. , 6. , 6. , 6. , 6. , 6. , 6.1, 6.1,
       6.1, 6.1, 6.1, 6.1, 6.2, 6.2, 6.2, 6.2, 6.3, 6.3, 6.3, 6.3, 6.3,
       6.3, 6.3, 6.3, 6.3, 6.4, 6.4, 6.4, 6.4, 6.4, 6.4, 6.4, 6.5, 6.5,
       6.5, 6.5, 6.5, 6.6, 6.6, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7,
       6.8, 6.8, 6.8, 6.9, 6.9, 6.9, 6.9, 7. , 7.1, 7.2, 7.2, 7.2, 7.3,
       7.4, 7.6, 7.7, 7.7, 7.7, 7.7, 7.9])

In [67]:
'''
任务5 去除该组数据中的重复值（任务提示：去重函数为 np.unique()。阅读参考文章④）
https://blog.csdn.net/yangyuwen_yang/article/details/79193770
'''
# 对于一维数组或者列表，unique函数去除其中重复的元素，并按元素由大到小返回一个新的无元素重复的元组

# c,s=np.unique(b,return_index=True) 
# return_index=True表示返回新列表元素在旧列表中的位置，并以列表形式储存在s中。
# print(c)
# print(s)

# a,s,p = np.unique(A, return_index=True, return_inverse=True)
# return_inverse=True 表示返回旧列表元素在新列表中的位置，并以列表形式储存在p中
# c,s,p = np.unique(iris,return_index=True,return_inverse=True )

data_new = np.unique(data)
data_new

array([4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5,
       5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8,
       6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.6, 7.7, 7.9])

In [68]:
'''
任务6：请利用 numpy 计算出该组花萼的平均长度（任务提示：平均函数为 np.mean()。阅读参考文章⑤）
https://blog.csdn.net/andybegin/article/details/84033216
'''

# mean_value = data.mean()
mean_value = np.mean(data)
mean_value

5.843333333333334

In [69]:
'''
任务7：用numpy计算出该组数据的标准差和方差，并得出相关结论（任务提示：标准差可以衡量数据的波动性。阅读参考文章⑥）
https://blog.csdn.net/Dawn510/article/details/89336650
'''

# 定义实现
# mean_list = np.array([round(mean_value,2)]*len(data))
# var = np.sum(np.square(data-mean_list))/len(data)
# std = np.sqrt(var)

np.var(data)
np.std(data)

0.8253012917851409

In [70]:
'''
任务8：求出所有花瓣累积总和（阅读参考文章⑦）
https://blog.csdn.net/wangxiao7474/article/details/78867390
sum() 没有axis参数表示全部数据相加
axis=0，表示按列相加
axis=1，表示按行相加
'''

np.sum(data)

876.5

In [71]:
'''
任务9：对已排序的 iris 数据进行累积求和运算
（任务提示：累积求和与求和有区别，累积求和是前几个数相加成新的元素从而组成新的数组。阅读参考文章⑧⑨）

https://blog.csdn.net/weixin_43486780/article/details/104692759

语法：numpy.cumsum(a, axis=None, dtype=None, out=None)
numpy中的cumsum函数按指定轴累加求和，返回中间结果组成的数组，在求累积分布时用到，这里是一维所以并没有指定轴
'''

np.cumsum(data_new)

array([  4.3,   8.7,  13.2,  17.8,  22.5,  27.3,  32.2,  37.2,  42.3,
        47.5,  52.8,  58.2,  63.7,  69.3,  75. ,  80.8,  86.7,  92.7,
        98.8, 105. , 111.3, 117.7, 124.2, 130.8, 137.5, 144.3, 151.2,
       158.2, 165.3, 172.5, 179.8, 187.2, 194.8, 202.5, 210.4])

In [72]:
'''
任务10：统计花萼长度比平均值 5.84 高的有多少（任务提示：例如 (arr>1).sum() 可统计大于1的个数）
'''

(data>mean_value).sum()

70